# Gitleaks configuration file

title = "Gitleaks Configuration"

[allowlist]
description = "Allowlisted files and paths"
paths = [
    "go.mod",
    "go.sum",
    "package-lock.json",
    "yarn.lock",
    "Gemfile.lock"
]

# Ignore certain file extensions
regexes = [
    ".*\\.html$",
    ".*\\.css$",
    ".*\\.scss$"
]

# Ignore commits from bots
commits = [
    "dependabot[bot]",
    "github-actions[bot]"
] 