# Name of your application. Used to uniquely configure containers.
service: my_app

# Name of the container image.
image: ankit.godara/my_app

# Deploy to these servers.
servers:
  web:
    - 192.168.0.1

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: app.example.com

# Credentials for your image host.
registry:
  username: ankit.godara
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true

# Aliases for common commands
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a persistent storage volume
volumes:
  - "my_app_storage:/rails/storage"

# Configure the image builder
builder:
  arch: amd64
  args:
    RUBY_VERSION: 3.4.3
